name: Build debug kernel
on:
  workflow_dispatch:

jobs:
  build-debug-kernel-a12:
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: android12-5.10
      version_name: android12-5.10.185
      tag: android12-5.10-2023-09
      os_patch_level: 2023-09
      patch_path: "5.10"
      debug: true
  build-debug-kernel-a13:
    strategy:
      matrix:
        include:
          - version: "5.10"
            sub_level: 187
            os_patch_level: 2023-08
          - version: "5.15"
            sub_level: 119
            os_patch_level: 2023-09
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: android13-${{ matrix.version }}
      version_name: android13-${{ matrix.version }}.${{ matrix.sub_level }}
      tag: android13-${{ matrix.version }}-${{ matrix.os_patch_level }}
      patch_path: ${{ matrix.version }}
      debug: true
