name: Build Android GKI Image
on:
  workflow_call:

jobs:
  build-a12-kernel:
    uses: ./.github/workflows/build-kernel-a12.yml
    secrets: inherit
  build-a13-kernel:
    uses: ./.github/workflows/build-kernel-a13.yml
    secrets: inherit
  build-a14-kernel:
    uses: ./.github/workflows/build-kernel-a14.yml
    secrets: inherit
  build-a15-kernel:
    uses: ./.github/workflows/build-kernel-a15.yml
    secrets: inherit
  build-a16-kernel:
    uses: ./.github/workflows/build-kernel-a16.yml
    secrets: inherit
