name: Build Android GKI Image
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Build debug kernel'
        required: false
        type: boolean
        default: false

jobs:
  build-a12-kernel:
    uses: ./.github/workflows/build-kernel-a12.yml
    secrets: inherit
    with:
      debug: ${{ github.event.inputs.debug || false }}
  build-a13-kernel:
    uses: ./.github/workflows/build-kernel-a13.yml
    secrets: inherit
    with:
      debug: ${{ github.event.inputs.debug || false }}
  build-a14-kernel:
    uses: ./.github/workflows/build-kernel-a14.yml
    secrets: inherit
    with:
      debug: ${{ github.event.inputs.debug || false }}
  build-a15-kernel:
    uses: ./.github/workflows/build-kernel-a15.yml
    secrets: inherit
    with:
      debug: ${{ github.event.inputs.debug || false }}
