name: ClangFormat check

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/clang-format.yml'
      - 'kernel/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/clang-format.yml'
      - 'kernel/**'

permissions:
  checks: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: check
        working-directory: kernel
        run: clang-format -Werror -n *.c
