name: ClangFormat check

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/clang-format.yml'
      - 'kernel/**/*.c'
      - 'kernel/**/*.h'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/clang-format.yml'
      - 'kernel/**/*.c'
      - 'kernel/**/*.h'
      - 'kernel/.clang-format'

permissions:
  checks: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: check
        working-directory: kernel
        run: make check-format
