name: Build ksuinit
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      os:
        required: false
        type: string
        default: ubuntu-latest
jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        
    - name: Setup rustup
      run: |
        rustup update stable

    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: userspace/ksuinit
        cache-targets: false

    - name: Build ksuinit
      run: |
        TARGET=${{ inputs.target }}
        LLVM_BIN=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin
        if [ "$TARGET" == "aarch64-linux-android" ]; then
          ARCH="aarch64"
          TARGET="aarch64-unknown-linux-musl"
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER="$LLVM_BIN/aarch64-linux-android26-clang"
          export RUSTFLAGS="-C link-arg=-no-pie"
        elif [ "$TARGET" == "x86_64-linux-android" ]; then
          ARCH="x86_64"
          TARGET="x86_64-unknown-linux-musl"
          export CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER="$LLVM_BIN/x86_64-linux-android26-clang"
        else
          exit 1
        fi
        rustup target add $TARGET
        cd userspace/ksuinit
        cargo build --target=$TARGET --release
        cp target/$TARGET/release/ksuinit ../../userspace/ksud/bin/$ARCH

    - name: Upload ksuinit artifact
      uses: actions/upload-artifact@v5
      with:
        name: ksuinit-${{ inputs.target }}
        path: userspace/ksuinit/target/**/release/ksuinit*
